package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/wau/wau-cli/internal/output"
)

var (
	initDir     string
	initAddr    string
	initRole    string
	initForce   bool
)

const defaultConfigTemplate = `# wau-cli configuration
# Generated by 'wau config init'

kernel:
  # Address of the WAU-core-kernel
  addr: "%s"

  # Agent role for RBAC: kernel_core | trusted_agent | external_agent
  role: "%s"

  # Timeout for HTTP requests
  timeout: 30s

  # Retry policy
  retry:
    max: 3
    backoff: 1s

# Output preferences
output:
  # Default format: table | json | yaml | csv
  format: "table"

  # Show colors in terminal output
  color: true

# Logging
logging:
  # Log level: debug | info | warn | error
  level: "info"

  # Log file (empty = stdout)
  file: ""
`

func newInitCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a default config file",
		Long: `Generate a default wau-cli configuration file.

By default, creates ~/.wau/config.yaml.`,
		Example: `  # Generate config in default location
  wau config init

  # Generate in specific directory
  wau config init --dir /path/to/dir

  # Overwrite existing config
  wau config init --force`,
		RunE: runInit,
	}

	cmd.Flags().StringVar(&initDir, "dir", "", "directory to create config in (default: ~/.wau/)")
	cmd.Flags().StringVar(&initAddr, "addr", "http://localhost:18400", "default kernel address")
	cmd.Flags().StringVar(&initRole, "role", "external_agent", "default agent role")
	cmd.Flags().BoolVar(&initForce, "force", false, "overwrite existing config file")

	return cmd
}

func runInit(cmd *cobra.Command, args []string) error {
	// Determine target directory
	dir := initDir
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			output.Error("Failed to get home directory: %v", err)
			return err
		}
		dir = filepath.Join(home, ".wau")
	}

	// Create directory if not exists
	if err := os.MkdirAll(dir, 0755); err != nil {
		output.Error("Failed to create directory %s: %v", dir, err)
		return err
	}

	configPath := filepath.Join(dir, "config.yaml")

	// Check if file exists
	if _, err := os.Stat(configPath); err == nil && !initForce {
		output.Warn("Config file already exists: %s", configPath)
		output.Info("Use --force to overwrite")
		return fmt.Errorf("config file exists, use --force to overwrite")
	}

	// Generate config content
	content := fmt.Sprintf(defaultConfigTemplate, initAddr, initRole)

	// Write to file
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		output.Error("Failed to write config file: %v", err)
		return err
	}

	output.Success("Config file created: %s", configPath)
	output.Info("Edit the file to customize your configuration")

	return nil
}
